"use client";
import { useEffect } from 'react';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import { Hamishe } from '../../public/fonts/fonts';
import Footer from '../components/Footer/Footer'; // Import Footer component
import { usePathname } from 'next/navigation';
import { ReactNode } from 'react';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const pathname = usePathname();

  useEffect(() => {
    const requestFullscreen = () => {
      if (!document.fullscreenElement) {
        document.documentElement.requestFullscreen().catch((err) => {
          console.error(
            `Error attempting to enable full-screen mode: ${err.message}`
          );
        });
      }
    };

    // Call the function on mount
    requestFullscreen();

    // Add an event listener to request full-screen mode on user interaction
    document.addEventListener('click', requestFullscreen);

    return () => {
      document.removeEventListener('click', requestFullscreen);
    };
  }, []);

  // List of routes where you want to show the footer
  const footerRoutes = [
    '/',
    '/smallCalendarMobile',
    '/FarakhorMobileDark',
    '/gahshomaranDark',
    '/ExtraTools',
    '/AiGenerator',
    '/PhoneAppGahshomar',
  ];

  return (
    <html lang='en' className={`${Hamishe.variable}`}>
      <Head>
        <title>{String(metadata.title)}</title>
        <meta
          name='description'
          content={metadata.description || 'Default Description'}
        />
        <meta name='theme-color' content='#4c5494' />
        <meta name='msapplication-navbutton-color' content='#4c5494' />
        <meta name='apple-mobile-web-app-status-bar-style' content='#4c5494' />
        <link rel='manifest' href='/manifest.json' />
        <link
          rel='icon'
          href='/assets/logo-mobile-gahshomar-main-page.png'
          sizes='192x192'
        />
        <link
          rel='apple-touch-icon'
          href='/assets/logo-mobile-gahshomar-main-page.png'
        />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&display=swap'
          rel='stylesheet'
        />
      </Head>
      <body className='Hamishe min-h-screen flex flex-col'>
        <main className='flex-grow'>{children}</main>
        {footerRoutes.includes(pathname) && <Footer />}{' '}
        {/* Conditionally render Footer */}
      </body>
    </html>
  );
}